app/nomination/routes.py
from flask import Blueprint, request, current_app, redirect, Response, url_for
from app import generate_uuid, is_development
from app.models import *
from sqlalchemy import func
from .nomination import UserNominationForm
from flask_cors import CORS

nominate_blueprint = Blueprint('nominate', __name__)
CORS(nominate_blueprint)


@nominate_blueprint.route('/nominate', methods=['GET', 'POST'])
def nomination():
    form = UserNominationForm()
    if request.method == 'GET':
        return render_template('nominate.html', form=form, template="form-template")
    
    elif request.method == 'POST':
        if form.validate_on_submit():
            if is_development():
                user = User.query.filter(User.jhed_id == 'dbelros1').first()
            else:
                user = User.query.filter(User.jhed_id == request.headers['UserPrincipalName']).first()

            if user is None:
                return "No User", 500

            project = Project.query.filter(func.lower(Project.name) == func.lower(form.data['name'])).first()
            if project is None:
                project = Project()
                project.id = generate_uuid()
                project.name = form.data['name']
                project.url = form.data['url']

                db.session.add(project)
                db.session.commit()

                db.session.refresh(project)

            nomination = Nomination()
            nomination.id = generate_uuid()
            nomination.user_id = user.id
            nomination.project_id = project.id

            db.session.add(nomination)
            db.session.commit()

            return redirect(url_for('nominate.success'))
            

@nominate_blueprint.route('/nominate/success', methods=['GET'])
def success():
    return render_template('nominate_success.html', template='form-template')

app/vote/routes.py
from flask import Blueprint, request, abort, render_template, jsonify, make_response, redirect, url_for
from flask_sqlalchemy import get_debug_queries
from app.models import *
from app import is_development, generate_uuid
from .vote import VoteForm
import json
from sqlalchemy import desc, and_
import datetime


from enum import IntFlag, auto

vote_blueprint = Blueprint('vote_blueprint', __name__)

@vote_blueprint.route('/vote', methods=['GET'])
@vote_blueprint.route('/vote/latest', methods=['GET'])
def vote_default():
    mydatetime = datetime.datetime.now()
    print("%s:%s" %(mydatetime, CampaignStatus.Active.value))
    campaign = Campaign.query.filter( and_ ( 
               Campaign.status_code == CampaignStatus.Active.value,
               Campaign.end_date > mydatetime,
               Campaign.start_date < mydatetime)).order_by(desc('start_date')).first()
    if campaign is not None:
        print(campaign.start_date + campaign.length)
        return(redirect(url_for('vote_blueprint.vote', campaign_id = campaign.id)))
    else:
        return(render_template('no-vote.html'))

@vote_blueprint.route('/vote/<campaign_id>', methods=['GET', 'POST'])
def vote(campaign_id = None):
    if campaign_id is None:
        return "test"

    if is_development():
        print("In development")
        user = User.query.filter(User.jhed_id == 'dbelros1').first()
    else:
        user = User.query.filter(User.jhed_id == request.headers['UserPrincipalName']).first()

    if user is None:
        abort(500)

    campaign = Campaign.query.filter(Campaign.id == campaign_id).first()
    if campaign is None:
        abort(500)
        
    form = VoteForm()
    print("vote route for %s", campaign_id)
    if request.method == 'GET':
        print(campaign_id)
        print(user.jhed_id)
        v = Vote.query.filter(Vote.user_id == user.id, Vote.campaign_id == campaign_id).first()
        if v is not None:
            return(render_template('vote_done.html', campaign=campaign, candidates=campaign.candidates, user=user, form=form))
        else:
            print("vote does not exist")
    elif request.method == 'POST':
        print(request.form)
        data = request.form
        print (data.get('jhed_id'))
        user = User.query.filter(User.jhed_id == data.get('jhed_id')).first()
        print(user)
        if user is None:
            abort(500)
            
        vote = Vote.query.filter(Vote.user_id == user.id, Vote.campaign_id == campaign_id).first()
        if vote is not None:
            return(render_template('vote_done.html', campaign=campaign, candidates=campaign.candidates, user=user, form=form))

        vote = Vote()
        vote.id = generate_uuid()
        vote.campaign_id = campaign_id
        vote.user_id = user.id
        print(data.get('votes'))
        print(json.dumps(data.get('votes')))
        vote.votes = data.get('votes')
        vote.date = datetime.datetime.now()
        db.session.add(vote)
        db.session.commit()

        return redirect(url_for('vote_blueprint.vote', campaign_id=campaign_id))

    
    return(render_template('vote_form.html', campaign=campaign, candidates=campaign.candidates, user=user, form=form))

app/templates/admin_base.html
{% extends 'base.html' %}

{% block local_menu %}
	      <li>
		<a class="nav-link" href="{{ url_for('admin_blueprint.list_campaigns') }}">
		  <img src="{{ url_for('static', filename='admin_panel_settings-black-18dp.svg')}}" height=24 width=24 />
		  Campaigns Admin
		</a>
	      </li>
	      <li>
		<a class="nav-link" href="{{ url_for('admin_blueprint.list_nominations') }}">
		  <img src="{{ url_for('static', filename='admin_panel_settings-black-18dp.svg')}}" height=24 width=24 />
		  Nominations Admin
		</a>
	      </li>
	      <li>
		<a class="nav-link" href="{{ url_for('admin_blueprint.list_projects') }}">
		  <img src="{{ url_for('static', filename='admin_panel_settings-black-18dp.svg')}}" height=24 width=24 />
		  Projects Admin
		</a>
	      </li>
	      <li>
		<a class="nav-link" href="{{ url_for('admin_blueprint.list_users') }}">
		  <img src="{{ url_for('static', filename='admin_panel_settings-black-18dp.svg')}}" height=24 width=24 />
		  Users Admin
		</a>
	      </li>
{% endblock local_menu %}

app/templates/admin_home.html
{% extends 'admin_base.html' %}

app/templates/admin_index.html
{% extends 'admin_home.html' %}


{% block title %}Administrative functions{% endblock title %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      Here there be dragons. A lot of this is a work in progress.  You might not get any feed back upon creating, deleting or editing things in here but you should be able do things such as:
      <ul class="list-group">
	<li class="list-group-item">Create and modify campaigns as well as add/remove candidates for the campaign</li>
	<li class="list-group-item">Create and modify nominations and projects</li>
	<li class="list-group-item">View all users on the system, make a user from this list an administrator.</li>
	<li class="list-group-item">View all votes from a campaign</li>
      </ul>
    </div>
  </div>
</div>
{% endblock content %}
      
		  

app/templates/create_campaign.html
<div class="form-wrapper">
  <h2 class="title">Create a New Campaign</h2>
  <form method="POST" action="{{ url_for('/admin/campaign/', 'add') }}">
    {{ form.csrf_token }}
    <fieldset class="form-field">
      {{ form.name.label }}
      {{ form.name(size=50) }}
    </fieldset>
  </form>
</div>

app/templates/error500.html
oh no, something went very wrong

app/templates/helpers.html
{% macro project_list(projects) -%}
<div>Other submitted projects:</div>
<div id="custom-search-input">
  <table class="table table-striped overflow-scroll vh-10 table-bordered">
    <thead>
      <tr>
	<th scope="col">#</th>
	<th scope="col">Project</th>
      </tr>
    </thead>
    <tbody>
      {% for project in projects %}
      <tr>
	<th scope="row">{{ loop.index }}</th>
	<td>{{ project.name }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
{%- endmacro %}

app/templates/list_nomination.html
{% extends 'admin_home.html' %}

{% block title %}Nominations{% endblock title %}

{% block content %}
<div class="container">
  <table class="table">
    {% for nomination in nominations %}
    <tr>
      <td>{{ nomination.project.name }}</td>
      <td>{{ nomination.project.url }}</td>
      <td>{{ nomination.user.jhed_id }}</td>
    </tr>
    {% endfor %}
  </table>
</div>
<div><a href="{{ url_for('admin_blueprint.create_nomination') }}"/>New</a></div>
{% endblock content %}

app/templates/list_projects.html
{% extends 'admin_home.html' %}

{% block content %}
<!-- Button trigger modal -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
      $('form#addForm').css('display', 'none')
      $('button#add').click(function(e) {
	  $('#addForm').toggle();
	  
	  e.preventDefault();
      });

      $('button#submit').click(function(e) {
	  var url = "{{ url_for('admin_blueprint.list_projects') }}"

	  $.ajax({
	      type: 'POST',
	      url: url,
	      data: $('form#addForm').serialize(),
	      success: function(data) {
		  console.log(data)
	      }
	  });
      })
  });
</script>

<div class="container">
  <div class="row flex-row-reverse">
    <div class="col-sm-1 col-1 mb-2">
      <button class="btn btn-primary" type="button" id="add">Add</button>
    </div>
    <div class="row mb-2">
      <div class="col-md-12 col-12">
	<form id="addForm">
	  {{ form.csrf_token }}
	  <div class="container border">
	    <div class="row">
	      <div class="col">
		<fieldset>
		  <div>{{ form.name.label(class_="form-label")}}</div>
		  <div>{{ form.name(class_="form-control")}}</div>
		</fieldset>
	      </div>
	      <div class="col">
		<fieldset>
		  <div>{{ form.url.label(class_="form-label")}}</div>
		  <div>{{ form.url(class_="form-control")}}</div>
		</fieldset>
	      </div>
	    </div>
	    <div class="row mb-2">
	      <div class="col-12">
		<fieldset>
		  <div>{{ form.description.label(class_="form-label") }}</div>
		  <div>{{ form.description(class_="form-control") }}</div>
		</fieldset>
	      </div>
	    </div>
	    <div class="row flex-row-reverse">
	      <div class="col-md-2 col-1"><button class="btn btn-secondary" type="button" id="submit">Submit</button></div>
	    </div>
	  </div>
	</form>
      </div>
    </div>
  </div>
  <div 
  <div class="row list-group">
  {% for project in projects %}
    <div class="container list-group-item">
      <div class="row">
	<div class="col-md-10">{{ project.name }}</div>
	<div class="col-md-2 content justify-content-end"><img src="{{ url_for('static', filename='mode_edit-24px.svg') }}" height=24 width=24></div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

app/templates/list_users.html
{% extends 'admin_home.html' %}

{% block content %}
<div class="container">
  <table class="table">
    {% for user in users %}
    <tr>
      <td><a href="{{ url_for('admin_blueprint.list_users', user_id=user.id) }}">{{ user.givenname }} {{ user.surname }}</a> {% if user.is_admin() %}(admin){% endif %}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock content %}

app/templates/no-vote.html
{% extends 'base.html' %}

{% block content %}
<div class="container-lg">
    The JHU Open-Source Programs Office runs FOSS Fund campaigns throughout the year. Please keep checking back and keep an eye on your email for our next one!
</div>
{% endblock %}
{% block title %}
There are no campaigns right now
{% endblock %}

app/templates/nominate.html
{% extends 'base.html' %}

{% block content %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
/*   $(document).ready(function(){
      $('button#submit').click(function() {

	  var form = $('form#nomination')
	  var url = "{{ url_for('nominate.nomination') }}"

	  $.ajax({
	      type: 'POST',
	      url: url,
	      data: form.serialize(),
	      success: function(data) {
		  window.location.replace("{{ url_for('nominate.success') }}")
	      }
	  });
      })
  }) */
</script>

<div class="container-lg">
  <form method="POST" id="nomination" action="{{ url_for('nominate.nomination') }}">
    {{ form.csrf_token }}
    <div class="row row-cols-2 justify-content-evenly">
      <div class="col">{{ form.name.label(class_="form-label") }} {{form.name(class_="form-control", list="id_datalist")}}
	<datalist id="id_datalist">
	  {% for project in projects %}
	  <option value="{{ project.name }}" id="{{ project.id }}">
	  {% endfor %}
	</datalist>
      </div>
      <div class="col">{{ form.url.label(class_="form-label") }} {{form.url(class_="form-control")}}</div>
    </div>
    <div class="row justify-content-evenly rol-cols-1">
      <div class="col align-items-middle">{{ form.reason.label(class_="form-label") }} {{ form.reason(class_="form-control") }}</div>
    </div>
    <div class="row rol-cols-4 mt-2">
      <div class="col-2"><button class="form-control btn btn-primary" type="submit" id="submit">Submit</button></div>
    </div>
  </form>
</div>

{% endblock %}
{% block title %}
Nominate Your Open Source Project
{% endblock %}

app/templates/user_detail.html
{% extends 'admin_home.html' %}

{% block content %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  $(document).ready(function() {
      $('#is_admin').change(function() {
	  var url = "{{ url_for('admin_blueprint.list_users', user_id=user.id)}}";
	  $.ajax({
	      type: "POST",
	      url: url,
	      data: $('form').serialize(),
	      success: function(data) {
		  console.log(data)
	      }
	  })
      });

      $.ajaxSetup({
	  beforeSend: function(xhr, settings) {
	      if(!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
		  xhr.setRequestHeader("X-CSRFToken", "{{ form.csrf_token._value() }}")
	      }
	  }
      })
  });
</script>


<div class="container">
  <form method="POST" id="foo">
    {{ form.csrf_token }}
    <div class="table">
      <div class="row">
	<div class="col">Name: </div>
	<div class="col">{{ user.givenname }} {{ user.surname }}</div>
      </div>
      <div class="row">
	<div class="col">Email: </div>
	<div class="col">{{ user.email }}</div>
      </div>
      <div class="row">
	<div class="col">JHED ID: </div>
	<div class="col">{{ user.jhed_id }}</div>
      </div>
      <div class="row">
	<div class="col">Administrator</div>
	<div class="col">{{ form.is_admin(checked=user.administrator) }}</div>
      </div>
    </div>
      <div class="container-md row">
	<div>Nominations: </div>
	<div class="panel-body">
	  <ul class="list-group">
	    {% for nomination in nominations %}
	    <li class="list-group-item">
	      <div class="row">
		<div class="col">{{ nomination.project.name }}</div>
		<div class="col justify-content-end">{{ nomination.nomination_date.strftime('%Y-%m-%d') }}</div>
	      </div>
	    </li>
	    {% endfor %}
	  </ul>
	</div>
      </div>
    </div>
  </form>
</div>
{% endblock content %}

app/templates/vote_done.html
{% extends 'base.html' %}

{% block title %}{{ campaign.title }}{% endblock title %}

{% block content %}
<div class="container-md">
  <div class="row"><h4>Thank You!</h4></div>
  <div class="row">
    <div class="col-12">
      Thank you for your vote. With your help, a Free and Open Source project will benefit from this month's FOSS Contributor Fund award. <br/><br/>
      Do you have a FOSS project that should be considered for the JHU FOSS Contributor Fund award? <a href="{{ url_for('nominate.nomination') }}">Nominate it!</a>
    </div>
  </div>
</div>
{% endblock content %}

app/templates/vote_form.html
{% extends 'base.html' %}

{% block title %}
{{ campaign.title }}
{% endblock title %}

{% block content %}
<script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
  $(document).ready(function() {
      updateVoteOrder();
      $(function() {
	  $("ul.sortable#candidates").sortable({
		update: function(event, ui) {
			updateVoteOrder();
		}
	});
      });
  });

  function updateVoteOrder() {
      var item_order = new Array();
      console.log("triggered")
      $('ul.sortable div').each(function() {
          item_order.push($(this).attr("id"));
      });

      $('input#order').val(JSON.stringify({ "votes": item_order}))
      console.log(item_order)
  }
</script>

<div class="container-lg">
  <div class="row">
    <div class="col-md mb-2 border-bottom">
      Order the projects below by preference and click 'Submit'. Your vote will be recorded and will help us decide which project will get the OSPO FOSS Contributor Fund award this month.
    </div>
  </div>
  <div class="row">
    <div class="col-8">
      {% for candidate in candidates %}
      <div class="row"><b>{{ candidate.project.name }} <a href="{{ candidate.url }}">{{ candidate.url }}</a></b></div>
      <div class="row">
	<div class="content mb-2" >{{ candidate.project.description }}</div>
      </div>
      {% endfor %}
    </div>
    <div class="col-4">
      <form method="POST" id="vote" class="form-control" action="{{ url_for('vote_blueprint.vote', campaign_id=campaign.id) }}">
		{{ form.csrf_token }}
		<input type="hidden" id="order" name="votes">
		<input type="hidden" name="jhed_id" value="{{ user.jhed_id }}" />
		<input type="hidden" name="campaign_id" value="{{ campaign.id }}" />
		<div class="row">
		  <div id="message">Order by preference</div>
		</div>
		<ul class="sortable list-group mb-2" id="candidates">
		  {% for candidate in candidates %}
		  <div class="list-group-item border sortable content ml=2" id="{{ candidate.id }}">{{ candidate.project.name }}</div>
		  {% endfor %}
		</ul>
		<div class="row flex-row-reverse">
		  <div class="col-md-6 content justify-content-end">
		    <button type="submit" class="btn btn-primary form-control" id="submit">Submit</button>
		  </div>
		</div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}